#!/bin/bash

# This is a general-purpose function to ask Yes/No questions in Bash, either
# with or without a default answer. It keeps repeating the question until it
# gets a valid answer.
ask() {
    # https://djm.me/ask
    local prompt default reply

    if [ "${2:-}" = "Y" ]; then
        prompt="Y/n"
        default=Y
    elif [ "${2:-}" = "N" ]; then
        prompt="y/N"
        default=N
    else
        prompt="y/n"
        default=
    fi

    while true; do

        # Ask the question (not using "read -p" as it uses stderr not stdout)
        echo -n "$1 [$prompt] "

        # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
        read reply </dev/tty

        # Default?
        if [ -z "$reply" ]; then
            reply=$default
        fi

        # Check if the reply is valid
        case "$reply" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac

    done
}

vundle_dir="$HOME/.vim/bundle/Vundle.vim"
if [ ! -d "$vundle_dir" ]; then
	git clone https://github.com/VundleVim/Vundle.vim.git "$vundle_dir"
fi

rcs=(".bashrc" ".vimrc")
for i in "${rcs[@]}" 
do
	dir="$HOME/${i}"
	copy_rc() {
		cp "$i" "$dir"
	}
	if [ -e "$dir" ]; then
		ask "$dir already exists, are you sure you want to replace it?" Y && copy_rc
	else
		copy_rc
	fi
done

